### ISSUE TITLE
Can't use ansible.builtin filters in rulebook

### ISSUE THREAD

**Issue by mooky31** [ansible/ansible-rulebook#691] opened 2024-06-05 16:08 UTC
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When I try to manipulate some data I want to sent to the playbook in extra_vars using ansible builtin filters, it fails

### Environment

Centos stream 9
```
$ ansible-rulebook --version
1.1.0
  Executable location = /home/bzjr2686/ansible-rulebook/venv/bin/ansible-rulebook
  Drools_jpy version = 0.3.9
  Java home = /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-3.el9.x86_64
  Java version = 17.0.6
  Python version = 3.9.18 (main, Jan 24 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
```

### Steps to reproduce

```
$ cat rule-test.yml
---
- name: Test webhook
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8081

  rules:
    - name: Run playbook
      condition: True
      action:
        run_playbook:
          name: play-test.yml
          extra_vars:
            testkey1: testval1
            testfilter1: "{{ event.payload.hostname | ansible.builtin.regex_replace('\\w+_(\\w+)', '\\1') }}"
```
`$ ansible-rulebook --rulebook rule-test.yml -i inventory.yaml`
`$ curl -k --header "Content-Type: application/json"  --data '{ "hostname": "ABC_Hostname" }'  http://localhost:8081`

### Actual results

`2024-06-05 18:02:09,481 - ansible_rulebook.rule_set_runner - ERROR - Error calling action run_playbook, err No filter named 'ansible.builtin.regex_replace'.`

### Expected results

Playbook starting with `testfilter1: Hostname` in extra_vars

**Comment by mkanoor** [comment] 2024-06-05 17:52
@mooky31 ansible playbook filters are not supported in ansible-rulebook. There is support for builtin in Jinja filters.
e.g.
```
- name: Replace Jinja filter
  hosts: all
  sources:
    - ansible.eda.generic:
        payload:
          - msg: hello_world
  rules:
    - name: Say Hello
      condition: true
      action:
        debug:
          msg: "This is a replace example {{ event.msg|replace('_','-') }}"
```
Or the other option to do is use the filter in the playbook vars section. All the event data would be passed into the playbook under **ansible_eda.** as extra vars and  there you can apply the ansible playbook filters. Example[](https://github.com/ansible/ansible-rulebook/blob/857ce658cae1b6dea4e05e87f384907c5b793793/tests/e2e/files/playbooks/print_event.yml#L7)

**Comment by mooky31** [comment] 2024-06-06 07:09
Ok thanks I understand I'll figure out something.
Are there any plan to support them ?

**Comment by Alex-Izquierdo** [comment] 2024-06-24 14:02
Hi @mooky31 There are no official plans to include it at this time. You can open a feature request. If we see traction we may consider it as a higher priority. 

I close this issue since it is not a bug.

**Closed by Alex-Izquierdo** 2024-06-24 14:02 UTC
